services:
  backend:
    build:
      context: ./backend
    container_name: realtime-backend
    ports:
      - "8000:8000"

  frontend-nicegui:
    build:
      context: ./frontend
    container_name: realtime-frontend-nicegui
    environment:
      BACKEND_WS_URL: ws://backend:8000/ws
    depends_on:
      - backend
    ports:
      - "8080:8080"
    profiles:
      - nicegui

  frontend-dash:
    build:
      context: ./frontend-dash
    container_name: realtime-frontend-dash
    environment:
      BACKEND_WS_URL: ws://backend:8000/ws
    depends_on:
      - backend
    ports:
      - "8080:8080"
    profiles:
      - dash
